#-*- coding: utf-8 -*-

{
	"name": "CreditCheck Inherited",
	"version": "1.0", 
	"depends": [
		'base',
		'vit_credit_check'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the CreditCheck module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		# "view/debitor.xml",
		# "view/credit_history.xml",
		# "view/owner.xml",
		"wizard/confirm.xml",
		"security/ir.model.access.csv",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}